### ISSUE TITLE
Is Socket's onOpen() callback called on successful Socket connection?

### ISSUE THREAD

**Issue by acrolink** [kuon/java-phoenix-channel#4]
Or is it only called on initializing / attempting a Socket connection?

**Comment by kuon** [comment]
It is triggered by the web socket implementation `onConnected`

http://takahikokawasaki.github.io/nv-websocket-client/com/neovisionaries/ws/client/WebSocketListener.html#onConnected-com.neovisionaries.ws.client.WebSocket-java.util.Map-

It should be triggered only on success, but I have not tested all possible failures.
