### ISSUE TITLE
question

### ISSUE THREAD

**Issue by codefist** [kuon/java-phoenix-channel#5]
How would you implement this inside the context of a modern compose android app?  I'm brand new to the android architecture, and my mind is blown by the platform bloat.
I'm thinking this would be a global singleton, I just don't know how or where to instantiate it and how to access it from my activities.
If the question is too involved, feel free to just delete this, but any direction is appreciated.  android is fucking crazy bloated.

**Comment by kuon** [comment]
Yes, create a single `Socket`.

The API is thread safe (but it will lock, so beware of deadlock).

I am personally not an Android developer, so I cannot guide you precisely, but I think the correct pattern is to use a `Service`.

Look at this:

https://developer.android.com/reference/android/app/Service

In your service, you would connect and disconnect the socket, and in your activity you write a client to the service. There is an example in the middle of the page.

I wish you luck.
